### ISSUE TITLE
kinto-lambda-blockpages_generator v3.2.0 not working on -prod

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/amo2kinto#79]
The latest kinto-lambda-blockpages_generator v3.2.0 is not working for Python 3.6 run time. We're seeing this error on -prod.

```
ds from /buckets/blocklists/collections/addons...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
Reading records from /buckets/blocklists/collections/plugins...
[WARNING]	2018-02-28T17:44:29.743Z	068f0194-1caf-11e8-b0fb-7f265a34aae0	Reading records from /buckets/blocklists/collections/plugins...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
Generating index...
[WARNING]	2018-02-28T17:44:30.403Z	068f0194-1caf-11e8-b0fb-7f265a34aae0	Generating index...
write() argument must be str, not bytes: TypeError
Traceback (most recent call last):
  File "/var/task/aws_lambda.py", line 238, in blockpages_generator
    generator_main(args)
  File "/var/task/amo2kinto/generator.py", line 121, in main
    generate(kinto_client, collections, args.target_dir, 'collection.tpl', 'record.tpl')
  File "/var/task/amo2kinto/generator.py", line 82, in generate
    generate_index(records, col_tpl, target_dir)
  File "/var/task/amo2kinto/generator.py", line 39, in generate_index
    f.write(res.encode('utf8'))
TypeError: write() argument must be str, not bytes

END RequestId: 068f0194-1caf-11e8-b0fb-7f265a34aae0
REPORT RequestId: 068f0194-1caf-11e8-b0fb-7f265a34aae0	Duration: 3192.11 ms	Billed Duration: 3200 ms 	Memory Size: 256 MB	Max Memory Used: 58 MB	
```

It doesn't work with python run time v2.7 either. The error being:

```
START RequestId: 32894d9f-1cb4-11e8-bacf-cf97e862fd59 Version: $LATEST
Syntax error in module 'aws_lambda': invalid syntax (__init__.py, line 65)

END RequestId: 32894d9f-1cb4-11e8-bacf-cf97e862fd59
REPORT RequestId: 32894d9f-1cb4-11e8-bacf-cf97e862fd59	Duration: 0.57 ms	Billed Duration: 100 ms 	Memory Size: 256 MB	Max Memory Used: 34 MB	
```

**Comment by leplatrem** [comment]
If I'm not mistaken this was fixed in #80
